FROM python:3.6

#RUN apt-get -y install python-pip
#RUN pip install --upgrade pip

RUN groupadd -r uwsgi && useradd -r -g uwsgi uwsgi
RUN apt install gcc
RUN apt policy net-tools
RUN pip install Flask uWSGI
WORKDIR /app
COPY app /app
COPY cmd.sh /
RUN chmod a+x /cmd.sh

EXPOSE 9090 9191
USER uwsgi

CMD ["/cmd.sh"]
